@startuml

Class models.Driver{
String license
String dni
String name
}

Class models.Vehicle{
int id
String plate
String brand
String model
Date dateFabrication
int numSeats
int numWheals
}

Class models.Trip{
Date date
String departure
String arrive
}

Class models.Passenger{
String dni
String name
String lastname
}

models.Trip "*" o-- "*" models.Passenger
models.Trip "*" *-- "1" models.Driver
models.Trip "*" *-- "1" models.Vehicle

Class controllers.DriverController{
	list()
	store()
	delete()
}

Class controllers.TripController{
	list()
	store()
	delete()
}

@enduml