<?php 
use Illuminate\Support\Facades\Schema;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
//Generated By PlantUML Command
class CreateBooks extends Migration{
	public function up(){ 
 		Schema::create('books', function (Blueprint $table) { 
			$table->bigIncrements('id');
			$table->string('title');
			$table->timestamps();
		});
 	} 
	public function down(){
 
	} 
}