name: CI

on: [push]

jobs:
  test:
    name: PHP Test on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
     strategy:
      max-parallel: 2
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@1.1.1
      with:
        php-version: 7.1
        extension-csv: mbstring
    - run: composer clearcache
