name: PHP Composer

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

     - name: Setup PHP
      with:
        php-version: 7.1
    - run: composer install

    - name: PHPUnit Tests
      run: vendor/bin/phpunit
      shell: bash
