name: CI

on: [push]

jobs:
  test:
    name: PHP Test 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@1.1.1
      with:
        php-version: 7.1
        extension-csv: mbstring
    - run: composer clearcache
    - name: PHPUnit Tests
      run: vendor/bin/phpunit
