name: CI

on: [push]

jobs:
  test:
    name: PHP Test on ${{ matrix.operating-system }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
